name: handy # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.95' # just for humans, typically '1.2+git' or '1.3.2'
summary: Handy the Atari Lynx emulator
description: |
  Handy the Atari Lynx emulator

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
icon:  handy_icon.png
title: Handy (SDL)

apps:
  handy:
    command: handy_sdl
parts:
  handy:
    # See 'snapcraft plugins'
    plugin: dump
    source: .
#    build-packages: [default-jre]
#    stage-packages: [default-jre]
    organize:
      handy: build/
      handy.1: man/man1/

architectures:
  - build-on: amd64

